apiVersion: v1
kind: Service
metadata:
  name: hello-world-app
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: hello-world-war
  type: LoadBalancer  
